# Development Environment KataGo FastAPI settings
katago.api.url=http://localhost:8000/api/analyze
analyze.cache.dir=C:/analyze_cache

# Favorite Player CSV Export settings
favorite.player.csv.dir=C:/Users/favor/OneDrive/Desktop/favokishi
favorite.player.csv.filename=favorite_players.csv
