name: Java CI with Gradle

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and Test with Gradle
      run: ./gradlew build --info
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 0
        JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
        LANG: ja_JP.UTF-8

    # GradleのprocessResourcesで除外したファイルを、Linuxのcpコマンドで手動コピー
    - name: Manually copy problematic resource
      run: |
        mkdir -p build/resources/main/static/images/players/
        cp "src/main/resources/static/images/players/辻󠄀篤仁.jpg" "build/resources/main/static/images/players/"

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/test-results/test/
